#!/bin/bash
# Save an approved improvement pattern to the knowledge base
# Usage: save-pattern.sh "pattern-name" "category" "description" [--force]
set -euo pipefail

PLUGIN_DIR="$(cd "$(dirname "$0")/.." && pwd)"
NAME="${1:-unnamed}"
CATEGORY="${2:-general}"
DESC="${3:-}"
FORCE=false

# Parse --force flag
for arg in "$@"; do
  if [ "$arg" = "--force" ]; then FORCE=true; fi
done

# Validate category
VALID_CATEGORIES="skill agent plugin memory config workflow general"
if ! echo "$VALID_CATEGORIES" | grep -qw "$CATEGORY"; then
  echo "Warning: category '$CATEGORY' is non-standard. Valid: $VALID_CATEGORIES" >&2
fi

# Sanitize name for filename (lowercase, dashes only)
SAFE_NAME=$(echo "$NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g' | sed 's/--*/-/g' | sed 's/^-\|-$//g')
FILE="$PLUGIN_DIR/knowledge/${CATEGORY}_${SAFE_NAME}.md"

# Check for existing pattern
if [ -f "$FILE" ] && [ "$FORCE" = false ]; then
  echo "Pattern already exists: $FILE"
  echo "Use --force to overwrite, or choose a different name."
  exit 1
fi

cat > "$FILE" <<EOF
---
name: $NAME
category: $CATEGORY
date: $(date -u +%F)
---

# $NAME

$DESC

## Implementation
<!-- How it was applied -->

## Result
<!-- What was gained -->
EOF

echo "Pattern saved: $FILE"

# Regenerate knowledge index
INDEX="$PLUGIN_DIR/knowledge/INDEX.md"
{
  echo "# Knowledge Index"
  echo ""
  echo "Auto-generated on $(date -u +%F). Do not edit manually — regenerated by save-pattern.sh"
  echo ""
  echo "| Name | Category | Date |"
  echo "|------|----------|------|"
  for f in "$PLUGIN_DIR/knowledge/"*.md; do
    [ -f "$f" ] || continue
    [ "$(basename $f)" = "INDEX.md" ] && continue
    fname=$(basename "$f" .md)
    cat_val=$(grep '^category:' "$f" 2>/dev/null | head -1 | sed 's/category: *//' || echo "unknown")
    date_val=$(grep '^date:' "$f" 2>/dev/null | head -1 | sed 's/date: *//' || echo "unknown")
    title=$(grep '^# ' "$f" 2>/dev/null | head -1 | sed 's/^# //' || echo "$fname")
    echo "| $title | $cat_val | $date_val |"
  done
} > "$INDEX"

echo "Index updated: $INDEX"
